POST {{host}}/register
Content-Type: application/json

{
  "name": "Ruben Vitt",
  "email": "dev@rubeen.dev",
  "password": "password"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "dev@rubeen.dev",
  "password": "password"
}

###
GET {{host}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldkBydWJlZW4uZGV2Iiwic3ViIjoiNWY4MmFmMGUzOGM2MjU1ODdhNDQ5NTA4IiwiaWF0IjoxNjAyNDAwMDI2LCJleHAiOjE2MDI0MDM2MjZ9.vZK3uTK-BZ1jR3qfWjW0IkL51siIkPgdXmiHlQ88X2k

###
GET {{host}}/api/shopping-lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldkBydWJlZW4uZGV2Iiwic3ViIjoiNWY4MmFmMGUzOGM2MjU1ODdhNDQ5NTA4IiwiaWF0IjoxNjAyNDAwMDI2LCJleHAiOjE2MDI0MDM2MjZ9.vZK3uTK-BZ1jR3qfWjW0IkL51siIkPgdXmiHlQ88X2k

###
POST {{host}}/api/shopping-lists/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldkBydWJlZW4uZGV2Iiwic3ViIjoiNWY4MmFmMGUzOGM2MjU1ODdhNDQ5NTA4IiwiaWF0IjoxNjAyNDAwMDI2LCJleHAiOjE2MDI0MDM2MjZ9.vZK3uTK-BZ1jR3qfWjW0IkL51siIkPgdXmiHlQ88X2k
Content-Type: application/json

{
  "name": "Testliste"
}
