POST {{host}}/register
Content-Type: application/json

{
  "name": "Ruben Vitt",
  "email": "dev@rubeen.dev",
  "password": "password"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "dev@rubeen.dev",
  "password": "password"
}

###
GET {{host}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldkBydWJlZW4uZGV2Iiwic3ViIjoiNWY3OTc3OGRiZmQyMDhiN2EyZjBhODRjIiwiaWF0IjoxNjAyMDk0NjM5LCJleHAiOjE2MDIwOTQ2OTl9.4FrMQIRfclCIir7og4GLx0ZHGozqIoc9-lvPyz62J2E

###
GET {{host}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaXNhIiwic3ViIjoyLCJpYXQiOjE2MDE2NDQ3NzAsImV4cCI6MTYwMTY0NDgzMH0.PkFxIvq2Owjagzjrt-aB8y3BGLSgycGxuLJMEBRSxOQ